config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard", as: :dashboard
  resources :fakes, only: [:show, :new] do
    resources :rentings, only: [:create]
    collection do
      get "/category/:category", to: "fakes#index", as: :index
      # get "/profile/:profile", to: "fakes#profile", as: :profile
    end
  end
  delete "renting/:id", to: "rentings#destroy", as: :doudou
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fake.rb
class Fake < ApplicationRecord
  validates :nickname, presence: true
  validates :url, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :personality, presence: true

  has_many :rentings
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :fake
  belongs_to :user
  
  validates :price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :rentings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fakes_controller.rb
class FakesController < ApplicationController
  def index
    @fakes = Fake.where(category: params[:category])
    @category = params[:category]
    @markers = @fakes.geocoded.map do |fake|
      {
        lat: fake.latitude,
        lng: fake.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: {fake: fake })
      }
    end
  end

  def show
    @fake = Fake.find(params[:id])
    @renting = Renting.new
  end

  def new
    @fake = Fake.new
  end
  def profile
    # @reservations = current_user.reservations
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
    @fakes = Fake.all
  end
  def dashboard
    @rentings = Renting.where(user: current_user)
  end
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  def new
  @fake = Fake.find(params[:fake_id])
  @renting = Renting.new
  end

  def create
    @fake = Fake.find(params[:fake_id])
    @renting = Renting.new(renting_params)
    @renting.fake = @fake
    @renting.user = current_user
   @renting.price = ((@renting.end_date - @renting.start_date).to_i)*@fake.price
    if @renting.save
      redirect_to dashboard_path(current_user)
    else
      render "fakes/show"
    end
  end

  def destroy
    @renting = Renting.find(params[:id])
    @renting.destroy
    redirect_to dashboard_path
  end

  private

  def renting_params
    params.require(:renting).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fakes/_info_window.html.erb
<hr><strong><%= fake.nickname %></strong></hr>
<hr><strong><%= fake.category %></strong></hr>
<hr><strong><%= fake.address %></strong></hr>

app/views/fakes/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("#{@category}.jpg") %>);">
  <div class="container">
    <h1><%= @category.capitalize %></h1>
    <p>Choose your best <%= @category %></p>
  </div>
</div>


<div class="container col-8">
  <div
  id="map"
  style="height: 600px; width: 100%"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-markers="<%= @markers.to_json %>"
  ></div>
</div>

<div class="container">
  <div class="cards">
    <% @fakes.each do |fake| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("#{fake.personality}.jpg") %>)">
        <%= link_to fake.nickname.capitalize, fake_path(fake) %>
        <p><%= fake.personality %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/fakes/show.html.erb
<div class="container">
  <div class="information">
    <%= image_tag(@fake.url) %>
    <div class="description">
      <h2>
        <%= @fake.nickname.capitalize %>
      </h2>
        <%= @fake.category %>
        <%= @fake.personality %>
        <p>
        <%= @fake.description %>
        </p>
        <p>
          <div class="price">
            <strong>price:  <%= @fake.price %></strong>$
          </div>
        </p>
          <% @fake.rating.to_i.times do  %>
            <i class="fas fa-heart"></i>
          <% end %>
      </div>
    </div>
    <hr>
    <%= simple_form_for([@fake, @renting]) do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <button type="submit"  class="btn btn-dark btn-lg btn-block">Book <%= @fake.nickname.capitalize %> </button>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

      <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Profile</h1>
<div class="container col-8">
  <div class="information">
    <img src="https://cdn.radiofrance.fr/s3/cruiser-production/2018/08/7c6275ae-2963-402d-87e4-09775db49e07/400x400_tupac_-_time_life_pictures.jpg" />
      <div class="card-product-infos">
        <h2><%= current_user.firstname.capitalize %></h2>
        <p><%= current_user.description %></p>

      </div>
  </div>
</div>


<div class="container col-8">
<h2 class="dashboard">Dashboard</h2>
  <div class="row">
    <div class="cards">
      <% @rentings.each do |rent|  %>
            <div class="card" style="width: 18rem;">
            <%= image_tag(rent.fake.url) %>
            <div class="card-body">
              <h5 class="card-title"><%=rent.fake.nickname.capitalize %></h5>
              <p class="card-text"><%=rent.fake.description %></p>
              <p>Price: <%=rent.price %> $</p>
              <%= link_to "Delete", doudou_path(rent), method: "delete" %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://s3-ap-southeast-2.amazonaws.com/media1.mydeal.com.au/blog/post/blog_image_20180219221810890.jpg);">
  <div class="container">
    <h1>A unique experience..</h1>
  </div>
</div>

<p id="notice"><%= notice %></p>

    <div class="cards">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("boss.jpg") %>)">
        <%= link_to  "Boss", index_fakes_path("boss") %>
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("friend.jpg") %>)">
        <%= link_to  "Friend", index_fakes_path("friend") %>
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("family.jpg") %>)">
        <%= link_to  "Family", index_fakes_path("family") %>
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("employee.jpg") %>)">
        <%= link_to  "Employee", index_fakes_path("employee") %>
      </div>
    </div>

app/views/pages/index.html.erb
<div class="home-banner">
  <h1>Le Wagon</h1>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= "Lorem ipsum dolor sit amet, consectetur adipisicing elit " * 100 %>
    </div>
  </div>
</div>

app/views/rentings/new.html.erb
<h3>Make money <i class="fas fa-dollar-sign"></i> with Rent me</h3>

<%= simple_form_for [fake, renting] do |f| %>
  <%= f.association :user, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= "Rent me" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://hiphopcorner.fr/wp-content/uploads/frontend/2018/11/image-tupac-amaru-shakur-blue.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "new", fake_rentings_path(:fake_id), class: "dropdown-item" %>
            <%= link_to "Profile",dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>